const BASENAME = 'USER';

const LOGIN_USER_INIT = `${BASENAME}_LOGIN_USER_INIT`;
const LOGIN_USER_SUCCESS = `${BASENAME}_LOGIN_USER_SUCCESS`;
const LOGIN_USER_FAIL = `${BASENAME}_LOGIN_USER_FAIL`;

export {LOGIN_USER_INIT, LOGIN_USER_SUCCESS, LOGIN_USER_FAIL};