const BASENAME = 'FIELD_';

const GET_FIELD_INIT = `${BASENAME}GET_FIELD_INIT`;
const GET_FIELD_SUCCESS = `${BASENAME}GET_FIELD_SUCCESS`;
const GET_FIELD_FAIL = `${BASENAME}GET_FIELD_FAIL`;

export {GET_FIELD_INIT, GET_FIELD_FAIL, GET_FIELD_SUCCESS};