const BASENAME = 'VISIT';

const POST_VISIT_INIT = `${BASENAME}_POST_VISIT_INIT`;
const POST_VISIT_SUCCESS = `${BASENAME}_POST_VISIT_SUCCESS`;
const POST_VISIT_FAIL = `${BASENAME}_POST_VISIT_FAIL`;

export {POST_VISIT_FAIL, POST_VISIT_INIT, POST_VISIT_SUCCESS};