const BASENAME = 'VISIT';

const POST_VISIT_INIT = `${BASENAME}_POST_VISIT_INIT`;
const POST_VISIT_SUCCESS = `${BASENAME}_POST_VISIT_SUCCESS`;
const POST_VISIT_FAIL = `${BASENAME}_POST_VISIT_FAIL`;

const GET_VISIT_INIT = `${BASENAME}_GET_VISIT_INIT`;
const GET_VISIT_SUCCESS = `${BASENAME}_GET_VISIT_SUCCESS`;
const GET_VISIT_FAIL = `${BASENAME}_GET_VISIT_FAIL`;

const GET_CURRENT_VISIT_INIT = `${BASENAME}_GET_CURRENT_VISIT_INIT`;
const GET_CURRENT_VISIT_SUCCESS = `${BASENAME}_GET_CURRENT_VISIT_SUCCESS`;
const GET_CURRENT_VISIT_FAIL = `${BASENAME}_GET_CURRENT_VISIT_FAIL`;

export {
    POST_VISIT_FAIL,
    POST_VISIT_INIT,
    POST_VISIT_SUCCESS,
    GET_VISIT_FAIL,
    GET_VISIT_INIT,
    GET_VISIT_SUCCESS,
    GET_CURRENT_VISIT_FAIL,
    GET_CURRENT_VISIT_INIT,
    GET_CURRENT_VISIT_SUCCESS
};