const BASENAME = 'PRODUCER';

const GET_PRODUCER_INIT = `${BASENAME}_GET_PRODUCER_INIT`;
const GET_PRODUCER_SUCCESS = `${BASENAME}_GET_PRODUCER_SUCCESS`;
const GET_PRODUCER_FAIL = `${BASENAME}_GET_PRODUCER_FAIL`;

export {GET_PRODUCER_INIT, GET_PRODUCER_SUCCESS, GET_PRODUCER_FAIL};