const BASENAME = 'LABOR_';

const GET_LABOR_INIT = `${BASENAME}GET_LABOR_INIT`;
const GET_LABOR_SUCCESS = `${BASENAME}GET_LABOR_SUCCESS`;
const GET_LABOR_FAIL = `${BASENAME}GET_LABOR_FAIL`;

export {GET_LABOR_FAIL, GET_LABOR_INIT, GET_LABOR_SUCCESS};