const BASENAME = 'LABOR_';

const GET_QUARTER_INIT = `${BASENAME}GET_QUARTER_INIT`;
const GET_QUARTER_SUCCESS = `${BASENAME}GET_QUARTER_SUCCESS`;
const GET_QUARTER_FAIL = `${BASENAME}GET_QUARTER_FAIL`;

export {GET_QUARTER_FAIL, GET_QUARTER_INIT, GET_QUARTER_SUCCESS};